apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  labels:
    app: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: ekvm
spec:
  type: LoadBalancer
  ports:
  - name: cmd
    protocol: TCP
    port: 21
    targetPort: 21
  - name: data
    protocol: TCP
    port: 20
    targetPort: 20
  - name: pasv
    protocol: TCP
    port: 13450
    targetPort: 13450
  selector:
    app: ftps

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deploy
  labels:
    app: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      restartPolicy: Always
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: cmd
        - containerPort: 20
          name: data
        - containerPort: 13450
          name: pasv
        livenessProbe:
          exec:
            command:
              - pgrep
              - vsftpd
          initialDelaySeconds: 1
          periodSeconds: 1
